[app]
; Путь к сетевой папке с ресурсами (буллеты, иконки, баннеры, config.json)
network_path_win = \\ks.rt.ru\dfs\BORUP\BORUP11\Отчет обученности Робот\server\email-builder
network_path_smb = //ks.rt.ru/dfs/BORUP/BORUP11/Отчет обученности Робот/server/email-builder
network_path_linux_hint = email-builder
; Порт локального сервера
port = 7788