"""
Synchronises the application version across all version carriers and provides
helpers for managing the admin license token.

Single source of truth: ``pyproject.toml`` ``[project] version``.

Targets updated by default run:
    * ``_version.py``   — imported by app.py (works in frozen .exe)
    * ``package.json``  — JS toolchain / npm scripts

Token workflow::

    # Step 1 (once): store the secret and bake its hash into the build
    python sync_version.py --gen-token SECRET
        Writes SECRET -> .key
        Writes sha256(SECRET) -> .admin_hash
        Build the exe — .admin_hash is embedded automatically.

    # Step 2 (per admin machine): produce the .lic from the stored .key
    python sync_version.py --make-lic
        Reads .key, writes .lic
        Distribute .lic next to the .exe on admin machines only.

Other commands::

    python sync_version.py                  # sync version
"""

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _read_pyproject_version() -> str:
    """Reads the version string from pyproject.toml."""
    text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    m = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    if not m:
        raise ValueError("version not found in pyproject.toml")
    return m.group(1)


def _write_version_py(version: str) -> None:
    """Regenerates _version.py with *version*."""
    content = (
        '"""\n'
        "Application version — auto-generated by sync_version.py.\n"
        "Do not edit manually; update pyproject.toml and run sync_version.py instead.\n"
        '"""\n'
        "\n"
        f'__version__ = "{version}"\n'
    )
    (ROOT / "src" / "_version.py").write_text(content, encoding="utf-8")
    print(f"  src/_version.py     -> {version}")


def _write_package_json(version: str) -> None:
    """Updates the version field in package.json."""
    path = ROOT / "package.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    data["version"] = version
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                    encoding="utf-8")
    print(f"  package.json        -> {version}")


def _gen_token(secret: str) -> None:
    """
    Stores the plaintext secret in ``.key`` and its SHA-256 hash in
    ``.admin_hash``.

    ``.key``        — keep in the project root (do NOT commit or distribute).
                      Used later by ``--make-lic`` to produce ``.lic`` files.
    ``.admin_hash`` — baked into the executable at build time via
                      ``build.spec``.  Must NOT be committed or shipped
                      as a standalone file.

    :param secret: Plaintext token to hash.
    """
    token_hash = hashlib.sha256(secret.encode("utf-8")).hexdigest()

    (ROOT / ".key").write_text(secret, encoding="utf-8")
    (ROOT / ".admin_hash").write_text(token_hash, encoding="utf-8")

    print(f".key written            : {ROOT / '.key'}")
    print(f".admin_hash written     : {ROOT / '.admin_hash'}")
    print(f"hash                    : {token_hash}")
    print()
    print("Next steps:")
    print("  1. Build the exe       — .admin_hash is baked in automatically.")
    print("  2. Run --make-lic      — produces .lic for distribution.")
    print("  3. Place .lic next to the .exe on admin machines only.")
    print("  4. Add .key, .admin_hash, .lic to .gitignore.")


def _make_lic() -> None:
    """
    Produces ``.lic`` from the stored ``.key`` file.

    If ``.key`` does not exist, prompts for the secret interactively,
    then creates both ``.key`` and ``.admin_hash`` before writing ``.lic``.

    ``.lic`` is the file that must be placed next to the ``.exe`` on every
    admin machine.  ``.key`` stays in the project root and is never
    distributed.
    """
    key_path = ROOT / ".key"
    if not key_path.exists():
        print(".key not found. Enter the secret to create it.")
        secret = input("Secret: ").strip()
        if not secret:
            print("Error: secret cannot be empty.")
            sys.exit(1)
        _gen_token(secret)

    secret = key_path.read_text(encoding="utf-8").strip()
    lic_path = ROOT / ".lic"
    lic_path.write_text(secret, encoding="utf-8")
    print(f".lic written            : {lic_path}")
    print("Distribute .lic next to the .exe on admin machines only.")


def main() -> None:
    """Entry point: sync version, generate token, or make .lic."""
    if len(sys.argv) == 3 and sys.argv[1] == "--gen-token":
        _gen_token(sys.argv[2])
        return

    if len(sys.argv) == 2 and sys.argv[1] == "--make-lic":
        _make_lic()
        return

    if len(sys.argv) > 1:
        print(f"Usage:")
        print(f"  {sys.argv[0]}                    sync version")
        print(f"  {sys.argv[0]} --gen-token SECRET  store secret + bake hash")
        print(f"  {sys.argv[0]} --make-lic          create .lic from .key")
        sys.exit(1)

    version = _read_pyproject_version()
    print(f"Syncing version {version} ...")
    _write_version_py(version)
    _write_package_json(version)
    print("Done.")


if __name__ == "__main__":
    main()
